### ISSUE TITLE
sync: consider supporting user-added documentation comments

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#186]
### Background
The context and current situation is this:
- To help the reader, each UUID in `tests.toml` is next to the value of the corresponding `description` key in `canonical-data.json`.
- We write the test description as a TOML comment.
- We decided that the value of the `description` key is [allowed to change](https://github.com/exercism/problem-specifications#test-data-canonical-datajson), which means that `configlet sync` should have the ability to update the comment.
- configlet's current implementation of "update each description comment" does so when runnning a bare `configlet sync` if there is a new test case, and it removes any extra comments or TOML data.

However, it seems like we should consider allowing maintainers to document in `tests.toml` the rationale for decisions.

From @angelikatyborska on Slack:
> What would be the best way to document why I'm choosing not to implement certain tests from problem specifications so that other maintainers in a year or two will still find it? I would put comments in `tests.toml`, but I think that file is supposed to get autoupdated at some point and the comments would be gone?

Some options are below.

---

### 1. Document only in the commit message and PR
It's possible to argue that this is sufficient, saying that a maintainer should see an instance of
```
some-uuid = false
```
and infer that there's a good reason for it to be `false`.

### 2. Document in a `.meta/design.md` file
Again from @angelikatyborska:
> concept exercises are supposed to have a `.meta/design.md` file, maybe a practice exercise should have that too? I would prefer to have comments in `tests.toml` that won't disappear too because that's the closest you can get to the source of truth for which tests you _want_ to implement

### 3a. Document in `tests.toml` - use the current format, but preserve user-added TOML comments
```toml
# first test description
bc310baa-ceae-4cb5-a656-20b7d2bbf1fe = true

# maintainer-added documentation comment

# second test description
3430d237-1ec8-4889-8f2d-17985d82e809 = false
```

With the current situation, adding extra comments in `tests.toml` is possible - it just means that a maintainer needs to to stage/discard changes at the line level when committing after running `sync`.

However, `configlet sync` can't know to which lines the comment applies, and whether the comment should apply to a new test case. That is, supporting such comments would require more care from maintainers after running `sync` - a comment in the wrong place could be misleading and worse than no comment at all.

We'd face at least these questions:
- If there's a new test case, should it always be put directly underneath the previous test case?
- If we add a new test case right at the top of `canonical-data.json`, should `configlet sync` add that test case above a non-generated comment that was previously at the top of the `tests.toml` file and documents the previously-first test case?

Another hurdle: parsing as TOML would no longer be sufficient - as you might expect, comments are not present in the end data structure after we parse as TOML (see https://github.com/exercism/configlet/issues/187).

### 3b. Document in `tests.toml` - use the current format, but preserve non-generated keys
```toml
# first test description
bc310baa-ceae-4cb5-a656-20b7d2bbf1fe = true

comment1 = "maintainer-added documentation comment"

# second test description
3430d237-1ec8-4889-8f2d-17985d82e809 = false
```

This feels ugly. It's like adding comments, but avoiding the `#` character.

### 3c. Document in `tests.toml` - use UUID as a table header
```toml
[bc310baa-ceae-4cb5-a656-20b7d2bbf1fe]
description = "first test description"
include = true
comment = "maintainer-added documentation comment"

[3430d237-1ec8-4889-8f2d-17985d82e809]
description = "second test description"
include = false
```

Then allow `sync` to update `description`, but make it preserve any other keys.

Note that the UUID doesn't need to be quoted - a valid unquoted table header contains only `[A-Za-z0-9_-]`. 

This option was inspired by @SaschaMann's suggestion of 
```toml
[uuid1]
description = ""
```
which I think is insufficient: we need to be explicit about excluding a test case unless we start including commit metadata like the time of the last update or the `problem-specifications` hash like
```
problem-specifications = 1a2b3c4d5e6f
```

**Comment by ErikSchierboom** [comment]
> 1. Document only in the commit message and PR

I think this is a little to indirect. Ideally, it would be immediately obvious to (new) contributors why a certain tests was included or excluded.

> 2. Document in a .meta/design.md file

Practice Exercises can have a `.meta/design.md` file, it is even in the latest spec: https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-metadesignmd The main advantage of this is that maintainers are expect to document design decisions in this file. The main disadvantage is that it is slightly indirect, as the `tests.toml` file can be seen as the _truth_. We could add an auto-generated comment to the `tests.toml` file stating that people should document things in the `.meta/design.md` file.

> 3a. Document in tests.toml - use the current format, but preserve user-added TOML comments

While this would in theory be great, I think the actual implementation would be difficult and require quite a bit of effort.

> 3b. Document in tests.toml - use the current format, but preserve non-generated keys

I agree that this looks quite ugly, so I'd rather not do this.

3c. Document in tests.toml - use UUID as a table header

I wouldn't mind this option, although it might still not be readily apparent to people that TOML comments would still be removed after syncing.

My personal preference would be option 2, with 3c as a second option.

**Comment by cmccandless** [comment]
I like 3c, with the following clarification that `include` defaults to `True` if missing.

**Comment by iHiD** [comment]
I like 3c. It keeps the `comment` near the `include`, and gives tracks the ability to add extra data for their own use. 

That said, this does involve more bulk PRs everywhere, which means this needs to happen ASAP, and also it means updating the syncer, which will take a day or so. So it's just been aware this knocks us back a day or two again in terms of launching. I'm 100% fine with that, but its just worth everyone being aware these "feature creeps" are adding up in terms of time-to-launch :) But also, we won't get a window of bulk-updating again in the future, so I think it's pragmatically right to do it.

**Comment by ErikSchierboom** [comment]
Just for completeness sake, one other option would be to do a combination of the above, where the description and include parts are indeed located in a nested table but comments could be added as regular:

```toml
# maintainer-added documentation comment
[bc310baa-ceae-4cb5-a656-20b7d2bbf1fe]
description = "first test description"
include = true
```

This does mean that writing updates becomes slightly more involved, as we'd have to detect the location of the `description` and `include` keys which the Nim TOML parser doesn't provide us with. However, it is not very hard so 🤷 

Oh and something else. We probably don't need the top-level `[canonical-tests]` key anymore, do we?

**Comment by ErikSchierboom** [comment]
The final spec is:

```toml
[<uuid>]
description = "<description>"
include = "<included>"
```

Each test case will be in its own table. With this format, we can selectively update the description and included value, while keeping any other properties left untouched.

## Comments

Comments can be added as properties (not as regular comments):

```toml
[<uuid>]
description = "<description>"
include = "<included>"
comment = "<comment>"
```

If a track was to use multiple comment lines, they can do so using an array:

```toml
[<uuid>]
description = "<description>"
include = "<included>"
comments = [
    "<comment-line-1>",
    "<comment-line-2>",
    "<comment-line-3>"
]
```

## Heading

To prevent maintainers from adding comments that will then be removed when running `configlet sync` again, we'll add the following heading to the file:

```toml
# This is an auto-generated file. Regular comments will be removed when this
# file is regenerated. Regenerating will not touch any manually added keys,
# so comments can be added in a "comment" key.
```

## Conversion

We've sent [bulk PRs](https://github.com/exercism/v3-launch/issues/22) to all tracks to convert the existing 

## configlet update

We'll change configlet to use this updated spec.
