### ISSUE TITLE
sync: produce `tests.toml` files that comply with the new spec

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#198]
The updated spec for `tests.toml` files stores each test case as follows:

```toml
[<uuid>]
description = "<description>"
include = "<included>"
```

Each test case will be in its own table. With this format, we can selectively update the description and included value, while keeping any other properties left untouched.

The discussion that led to this format is in https://github.com/exercism/configlet/issues/186.

## Defaults

As the default case will be to include a test case, we only require `include` to be specified when its value is `false`. Therefore:

```toml
[1e22cceb-c5e4-4562-9afe-aef07ad1eaf4]
description = "basic"
include = true
```

is equivalent to:

```toml
[1e22cceb-c5e4-4562-9afe-aef07ad1eaf4]
description = "basic"
````

When writing new, included test cases, configlet will output them in the second format (without `include = true`). If configlet is updating an existing test case, it will retain the format used in the source file.

## Comments

Comments can be added as properties (not as regular comments):

```toml
[<uuid>]
description = "<description>"
include = "<included>"
comment = "<comment>"
```

If a track was to use multiple comment lines, they can do so using an array:

```toml
[<uuid>]
description = "<description>"
include = "<included>"
comments = [
    "<comment-line-1>",
    "<comment-line-2>",
    "<comment-line-3>"
]
```

## Heading

To prevent maintainers from adding comments that will then be removed when running `configlet sync` again, we'll add the following heading to the file:

```toml
# This is an auto-generated file. Regular comments will be removed when this
# file is regenerated. Regenerating will not touch any manually added keys,
# so comments can be added in a "comment" key.
```

## Example

```toml
# This is an auto-generated file. Regular comments will be removed when this
# file is regenerated. Regenerating will not touch any manually added keys,
# so comments can be added in a "comment" key.

[1e22cceb-c5e4-4562-9afe-aef07ad1eaf4]
description = "basic"

[79ae3889-a5c0-4b01-baf0-232d31180c08]
description = "lowercase words"
include = false

[ec7000a7-3931-4a17-890e-33ca2073a548]
description = "invalid input"
include = false
comment = "excluded because we don't want to add error handling to the exercise"
```

## Conversion

We've sent [bulk PRs](https://github.com/exercism/v3-launch/issues/22) to all tracks to convert the existing `tests.toml` files.

We will sent a future update to remove the `include = true` statements.
