### ISSUE TITLE
sync: allow omitting `include = true` in tests.toml?

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#207]
In #186 we changed the spec for `tests.toml`, but we didn't state how a missing `include` property is handled. 

We could:
1. Forbid `include` to be missing, making it produce an error in `configlet`
2. Allow `include` to be missing, making it imply `include = true` and...
   2a. Recommend against omitting `include = true` - warn about it in `configlet`
   2b. Encourage track maintainers to do what they prefer - don't warn about it in `configlet`. `configlet sync` could gain an option that controls whether `tests.toml` are generated with `include = true`, but this might be overkill.
   2c. Encourage omitting `include = true`, making `configlet sync` omit it when generating `tests.toml` files. Batch PR to update tracks to remove `include = true`. 
   2d. Like 2c, but also make `include = true` a warning/error.

From https://github.com/exercism/configlet/issues/186#issuecomment-784292059 it seems at least @cmccandless and @SaschaMann would like us to support omitting `include = true`.

My own preference is the same, arguing that it generally improves readability: excluded tests are significantly rarer, and are likely to remain so for the foreseeable future - omitting `include = true` makes the exceptional cases more obvious.

Comparison for the `triangle` exercise on the Nim track (spot the excluded tests):
```toml
[8b2c43ac-7257-43f9-b552-7631a91988af]
description = "all sides are equal"
include = true

[33eb6f87-0498-4ccf-9573-7f8c3ce92b7b]
description = "any side is unequal"
include = true

[c6585b7d-a8c0-4ad8-8a34-e21d36f7ad87]
description = "no sides are equal"
include = true

[16e8ceb0-eadb-46d1-b892-c50327479251]
description = "all zero sides is not a triangle"
include = true

[3022f537-b8e5-4cc1-8f12-fd775827a00c]
description = "sides may be floats"
include = false

[cbc612dc-d75a-4c1c-87fc-e2d5edd70b71]
description = "last two sides are equal"
include = true

[e388ce93-f25e-4daf-b977-4b7ede992217]
description = "first two sides are equal"
include = true

[d2080b79-4523-4c3f-9d42-2da6e81ab30f]
description = "first and last sides are equal"
include = true

[8d71e185-2bd7-4841-b7e1-71689a5491d8]
description = "equilateral triangles are also isosceles"
include = true

[840ed5f8-366f-43c5-ac69-8f05e6f10bbb]
description = "no sides are equal"
include = true

[2eba0cfb-6c65-4c40-8146-30b608905eae]
description = "first triangle inequality violation"
include = true

[278469cb-ac6b-41f0-81d4-66d9b828f8ac]
description = "second triangle inequality violation"
include = true

[90efb0c7-72bb-4514-b320-3a3892e278ff]
description = "third triangle inequality violation"
include = true

[adb4ee20-532f-43dc-8d31-e9271b7ef2bc]
description = "sides may be floats"
include = false

[e8b5f09c-ec2e-47c1-abec-f35095733afb]
description = "no sides are equal"
include = true

[2510001f-b44d-4d18-9872-2303e7977dc1]
description = "all sides are equal"
include = true

[c6e15a92-90d9-4fb3-90a2-eef64f8d3e1e]
description = "two sides are equal"
include = true

[70ad5154-0033-48b7-af2c-b8d739cd9fdc]
description = "may not violate triangle inequality"
include = true

[26d9d59d-f8f1-40d3-ad58-ae4d54123d7d]
description = "sides may be floats"
include = false
```

vs

```toml
[8b2c43ac-7257-43f9-b552-7631a91988af]
description = "all sides are equal"

[33eb6f87-0498-4ccf-9573-7f8c3ce92b7b]
description = "any side is unequal"

[c6585b7d-a8c0-4ad8-8a34-e21d36f7ad87]
description = "no sides are equal"

[16e8ceb0-eadb-46d1-b892-c50327479251]
description = "all zero sides is not a triangle"

[3022f537-b8e5-4cc1-8f12-fd775827a00c]
description = "sides may be floats"
include = false

[cbc612dc-d75a-4c1c-87fc-e2d5edd70b71]
description = "last two sides are equal"

[e388ce93-f25e-4daf-b977-4b7ede992217]
description = "first two sides are equal"

[d2080b79-4523-4c3f-9d42-2da6e81ab30f]
description = "first and last sides are equal"

[8d71e185-2bd7-4841-b7e1-71689a5491d8]
description = "equilateral triangles are also isosceles"

[840ed5f8-366f-43c5-ac69-8f05e6f10bbb]
description = "no sides are equal"

[2eba0cfb-6c65-4c40-8146-30b608905eae]
description = "first triangle inequality violation"

[278469cb-ac6b-41f0-81d4-66d9b828f8ac]
description = "second triangle inequality violation"

[90efb0c7-72bb-4514-b320-3a3892e278ff]
description = "third triangle inequality violation"

[adb4ee20-532f-43dc-8d31-e9271b7ef2bc]
description = "sides may be floats"
include = false

[e8b5f09c-ec2e-47c1-abec-f35095733afb]
description = "no sides are equal"

[2510001f-b44d-4d18-9872-2303e7977dc1]
description = "all sides are equal"

[c6e15a92-90d9-4fb3-90a2-eef64f8d3e1e]
description = "two sides are equal"

[70ad5154-0033-48b7-af2c-b8d739cd9fdc]
description = "may not violate triangle inequality"

[26d9d59d-f8f1-40d3-ad58-ae4d54123d7d]
description = "sides may be floats"
include = false
```
