### ISSUE TITLE
sync: Add `reimplements` property to `tests.toml` file

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#316]
Having a `reimplements` property added to the `tests.toml` file helps  identify re-implemented test cases:

```toml
[b9228bb1-465f-4141-b40f-1f99812de5a8]
description = "disallow first strand longer"
reimplements = "919f8ef0-b767-4d1b-8516-6379d07fcb28"
```
